'use client'

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

export function PromotionalCampaignSummary({ campaigns = [] }) {
  return (
    <Card className="rounded-2xl border-0 bg-gradient-to-br from-amber-400/10 via-yellow-300/5 to-orange-400/10 shadow-sm overflow-hidden">
      <CardHeader className="pb-2 pt-4 px-4 border-b border-amber-200/60">
        <CardTitle className="text-sm font-semibold text-slate-800">Promotional Campaigns</CardTitle>
        <p className="text-[11px] text-slate-600">Bookings and revenue generated by campaigns.</p>
      </CardHeader>
      <CardContent className="p-0">
        {campaigns.length === 0 ? (
          <p className="text-xs text-slate-500 py-6 text-center">No campaign data in this range.</p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="bg-amber-100/80 border-b border-amber-200/60">
                  <th className="text-left py-2.5 px-3 font-semibold text-slate-700">Campaign</th>
                  <th className="text-right py-2.5 px-3 font-semibold text-slate-700">Bookings</th>
                  <th className="text-right py-2.5 px-3 font-semibold text-slate-700">Revenue</th>
                </tr>
              </thead>
              <tbody>
                {campaigns.map((c) => (
                  <tr key={c.campaign} className="border-b border-slate-100 hover:bg-amber-50/60">
                    <td className="py-2 px-3 font-medium text-slate-800">{c.campaign}</td>
                    <td className="py-2 px-3 text-right text-slate-700">
                      {c.bookings?.toLocaleString('en-IN') || 0}
                    </td>
                    <td className="py-2 px-3 text-right text-slate-700">
                      ₹{' '}
                      {c.revenue?.toLocaleString('en-IN', {
                        maximumFractionDigits: 0,
                      }) || 0}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

