'use client'

import { useState } from "react"
import { useAuth } from "@/app/auth-context"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { AlertTriangle, Zap, CheckCircle2 } from "lucide-react"
import type { KitchenKOT } from "./KitchenKOT"

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000"

interface Props {
  bills: any[]
  kots: KitchenKOT[]
  onRefresh: () => void
}

export default function AutoGenerateKOT({ bills, kots, onRefresh }: Props) {
  const { user } = useAuth()
  const [generating, setGenerating] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)

  const billsWithoutKOT = bills.filter((bill) => {
    if (!bill || !bill.id) return false
    const billStatus = bill.status || "Pending"
    const hasKOT = kots.some((kot) => kot.billId === bill.id)
    return (billStatus === "Paid" || billStatus === "On Hold") && !hasKOT
  })

  const handleAutoGenerate = async (billId: string) => {
    if (!user?.hotelId) return

      const bill = bills.find((b) => b && b.id === billId)
      if (!bill) {
        setError("Bill not found")
        return
      }
      const billItems = Array.isArray(bill.items) ? bill.items : []
      if (billItems.length === 0) {
        setError("Bill has no items")
        return
      }

    setGenerating(billId)
    setError(null)
    try {
      const token = typeof window !== "undefined" ? localStorage.getItem("token") : null
      const res = await fetch(
        `${API_BASE}/api/hotel-data/${user.hotelId}/kitchen-kots`,
        {
          method: "POST",
          headers: {
            Authorization: token ? `Bearer ${token}` : "",
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            billId: bill.id,
            tableNo: bill.tableNo,
            guestName: bill.guestName || null,
            items: billItems.map((item: any) => ({
              id: item.id || String(Math.random()),
              name: item.name || "Unknown Item",
              quantity: Number(item.quantity || 1),
              section: item.section || null,
              notes: item.notes || null,
              status: "Pending",
            })),
            autoGenerated: true,
            status: "Pending",
          }),
        },
      )

      if (!res.ok) {
        const data = await res.json().catch(() => ({}))
        throw new Error((data as any)?.message || `Failed to generate KOT (HTTP ${res.status})`)
      }

      onRefresh()
    } catch (e: any) {
      console.error(e)
      setError(e?.message || "Failed to auto-generate KOT")
    } finally {
      setGenerating(null)
    }
  }

  return (
    <section className="space-y-3">
      <Card className="rounded-2xl bg-linear-to-r from-orange-500 to-amber-500 text-white shadow-sm border-none">
        <CardContent className="p-3 flex items-center justify-between">
          <div>
            <div className="text-[11px] uppercase tracking-wide opacity-80">
              Bills without KOT
            </div>
            <div className="text-lg font-semibold">
              {billsWithoutKOT.length.toString().padStart(2, "0")}
            </div>
          </div>
          <Zap className="h-8 w-8 opacity-80" />
        </CardContent>
      </Card>

      {error && (
        <Card className="border border-red-100 bg-red-50 rounded-xl">
          <CardContent className="p-2.5 flex items-center gap-2 text-xs text-red-800">
            <AlertTriangle className="h-4 w-4" />
            <span>{error}</span>
          </CardContent>
        </Card>
      )}

      <Card className="rounded-2xl border border-slate-200 bg-white shadow-sm">
        <CardHeader className="pb-2 pt-3 px-3">
          <CardTitle className="text-sm font-semibold text-slate-900">
            Automatically generate KOT when order is confirmed
          </CardTitle>
        </CardHeader>
        <CardContent className="p-3 pt-0">
          <div className="space-y-2">
            {billsWithoutKOT.length === 0 ? (
              <div className="py-8 text-center text-xs text-slate-400">
                All paid bills have KOTs generated. KOTs are automatically created when orders are confirmed and paid.
              </div>
            ) : (
              billsWithoutKOT.map((bill) => (
                <div
                  key={bill.id}
                  className="flex items-center justify-between p-2.5 rounded-lg border border-slate-200 bg-slate-50/50"
                >
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-medium text-slate-900">
                        Table {bill.tableNo}
                      </span>
                      <Badge className="border text-[10px] bg-green-100 text-green-700 border-green-200">
                        Paid
                      </Badge>
                    </div>
                    <div className="text-[11px] text-slate-500 mt-0.5">
                      {bill.items?.length || 0} items • ₹{Number(bill.totalAmount || 0).toFixed(2)}
                      {bill.guestName && ` • Guest: ${bill.guestName}`}
                    </div>
                  </div>
                  <Button
                    size="sm"
                    className="h-7 px-2 text-xs bg-orange-600 hover:bg-orange-700"
                    onClick={() => handleAutoGenerate(bill.id)}
                    disabled={generating === bill.id}
                  >
                    {generating === bill.id ? "Generating..." : "Generate KOT"}
                  </Button>
                </div>
              ))
            )}
          </div>
        </CardContent>
      </Card>

      <Card className="rounded-2xl border border-blue-200 bg-blue-50 shadow-sm">
        <CardContent className="p-3">
          <div className="flex items-start gap-2">
            <CheckCircle2 className="h-4 w-4 text-blue-600 mt-0.5 shrink-0" />
            <div className="text-xs text-blue-800">
              <div className="font-semibold mb-1">Auto-generate feature:</div>
              <div className="text-[11px] space-y-0.5">
                <div>• KOTs are automatically generated when bills are marked as "Paid"</div>
                <div>• Each KOT gets a unique number (KOT-YYYYMMDD-XXX)</div>
                <div>• Items from the bill are copied to the KOT</div>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </section>
  )
}
