'use client'

import { useEffect, useState } from "react"
import { useAuth } from "@/app/auth-context"
import { Card, CardContent } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
  AlertTriangle,
  RefreshCw,
  ChefHat,
} from "lucide-react"
import AutoGenerateKOT from "./AutoGenerateKOT"
import SendToKitchen from "./SendToKitchen"
import ModifyOrder from "./ModifyOrder"
import CancelItem from "./CancelItem"
import KOTPrinting from "./KOTPrinting"
import OrderStatusTracking from "./OrderStatusTracking"
import SectionWiseKOT from "./SectionWiseKOT"
import PreparationTimeTracking from "./PreparationTimeTracking"
import ChefAssignment from "./ChefAssignment"
import ReprintKOT from "./ReprintKOT"

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000"

export interface KitchenKOT {
  id: string
  kotNumber: string
  billId: string
  tableNo: string
  guestName: string | null
  items: Array<{
    id: string
    name: string
    quantity: number
    section?: string
    notes?: string
    status?: string
    preparationTime?: number
  }>
  section: string | null
  status: "Pending" | "Preparing" | "Ready" | "Cancelled" | "Completed"
  assignedChefId: string | null
  assignedChefName: string | null
  preparationStartTime: string | null
  preparationEndTime: string | null
  estimatedTime: number | null
  printedAt: string | null
  printCount: number
  notes: string | null
  autoGenerated: boolean
}

export default function KitchenKOT() {
  const { user } = useAuth()
  const [kots, setKots] = useState<KitchenKOT[]>([])
  const [bills, setBills] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const loadData = async () => {
    if (!user?.hotelId) {
      setError("Hotel not selected. Please login again.")
      setLoading(false)
      return
    }

    const token =
      typeof window !== "undefined" ? localStorage.getItem("token") : null
    if (!token) {
      setError("Not authenticated. Please log in again.")
      setLoading(false)
      return
    }

    setLoading(true)
    setError(null)

    try {
      const [kotsRes, billsRes] = await Promise.all([
        fetch(
          `${API_BASE}/api/hotel-data/${user.hotelId}/kitchen-kots`,
          { headers: { Authorization: `Bearer ${token}` } },
        ),
        fetch(
          `${API_BASE}/api/hotel-data/${user.hotelId}/restaurant-bills`,
          { headers: { Authorization: `Bearer ${token}` } },
        ),
      ])

      if (!kotsRes.ok) {
        const errorText = await kotsRes.text().catch(() => "")
        console.error("KOTs fetch error:", kotsRes.status, errorText)
        throw new Error(`Failed to fetch KOTs (HTTP ${kotsRes.status})`)
      }

      if (!billsRes.ok) {
        const errorText = await billsRes.text().catch(() => "")
        console.error("Bills fetch error:", billsRes.status, errorText)
        // Don't throw for bills, just log
        console.warn("Failed to fetch bills, continuing with empty list")
      }

      const kotsJson = await kotsRes.json().catch(() => ({}))
      const billsJson = billsRes.ok ? await billsRes.json().catch(() => ({})) : {}

      console.log("KOTs response:", kotsJson)
      console.log("Bills response:", billsJson)

      const kotsList = (kotsJson as any).kots || []
      setKots(
        kotsList.map((k: any) => ({
          id: String(k.id),
          kotNumber: String(k.kotNumber || ""),
          billId: String(k.billId || ""),
          tableNo: String(k.tableNo || ""),
          guestName: k.guestName ? String(k.guestName) : null,
          items: Array.isArray(k.items) ? k.items : [],
          section: k.section ? String(k.section) : null,
          status: k.status || "Pending",
          assignedChefId: k.assignedChefId ? String(k.assignedChefId) : null,
          assignedChefName: k.assignedChefName ? String(k.assignedChefName) : null,
          preparationStartTime: k.preparationStartTime ? String(k.preparationStartTime) : null,
          preparationEndTime: k.preparationEndTime ? String(k.preparationEndTime) : null,
          estimatedTime: k.estimatedTime != null ? Number(k.estimatedTime) : null,
          printedAt: k.printedAt ? String(k.printedAt) : null,
          printCount: Number(k.printCount || 0),
          notes: k.notes ? String(k.notes) : null,
          autoGenerated: Boolean(k.autoGenerated),
        })),
      )

      const billsList = (billsJson as any).bills || []
      setBills(billsList)
      console.log(`[KitchenKOT] Loaded ${kotsList.length} KOTs and ${billsList.length} bills`)
      console.log(`[KitchenKOT] KOTs:`, kotsList)
      console.log(`[KitchenKOT] Bills:`, billsList)
    } catch (e: any) {
      console.error("Load data error:", e)
      setError(
        e instanceof Error
          ? e.message
          : "Failed to load kitchen KOT data. Please try again.",
      )
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    if (user?.hotelId) {
      loadData()
    }
  }, [user?.hotelId])

  if (!user?.hotelId) {
    return (
      <main className="p-4 space-y-4 bg-[#f3f4f6] min-h-[calc(100vh-3rem)]">
        <div className="pb-1">
          <h1 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
            <ChefHat className="h-4 w-4 text-orange-600" />
            Kitchen KOT management
          </h1>
        </div>
        <Card className="rounded-2xl border border-red-200 bg-red-50">
          <CardContent className="p-6 flex items-center gap-2 text-sm text-red-800">
            <AlertTriangle className="h-5 w-5" />
            <span>Hotel not selected. Please login again.</span>
          </CardContent>
        </Card>
      </main>
    )
  }

  if (loading) {
    return (
      <main className="p-4 space-y-4 bg-[#f3f4f6] min-h-[calc(100vh-3rem)]">
        <div className="pb-1">
          <h1 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
            <ChefHat className="h-4 w-4 text-orange-600" />
            Kitchen KOT management
          </h1>
          <p className="text-xs text-slate-500 mt-0.5">Loading KOT data…</p>
        </div>
        <Card className="rounded-2xl border border-slate-200 bg-white">
          <CardContent className="p-6 flex items-center justify-center text-sm text-slate-500">
            Loading kitchen orders and bills from backend…
          </CardContent>
        </Card>
      </main>
    )
  }

  const statusCounts = {
    Pending: kots.filter((k) => k.status === "Pending").length,
    Preparing: kots.filter((k) => k.status === "Preparing").length,
    Ready: kots.filter((k) => k.status === "Ready").length,
    Completed: kots.filter((k) => k.status === "Completed").length,
    Cancelled: kots.filter((k) => k.status === "Cancelled").length,
  }

  return (
    <main className="p-4 space-y-4 bg-[#f3f4f6] min-h-[calc(100vh-3rem)]">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
            <ChefHat className="h-4 w-4 text-orange-600" />
            Kitchen KOT management
          </h1>
          <p className="text-xs text-slate-500 mt-0.5">
            Manage Kitchen Order Tickets, track preparation status, assign chefs, and print KOTs.
          </p>
        </div>
        <button
          type="button"
          onClick={loadData}
          disabled={loading || !user?.hotelId}
          className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border border-slate-200 bg-white text-xs font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-50"
        >
          <RefreshCw className="h-3.5 w-3.5" />
          Refresh
        </button>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-5 gap-2">
        <Card className="rounded-xl bg-linear-to-r from-orange-500 to-amber-500 text-white shadow-sm border-none">
          <CardContent className="p-3 flex flex-col gap-1">
            <span className="text-[11px] uppercase tracking-wide opacity-80">
              Total KOTs
            </span>
            <span className="text-lg font-semibold">
              {kots.length.toString().padStart(2, "0")}
            </span>
          </CardContent>
        </Card>
        <Card className="rounded-xl bg-linear-to-r from-blue-500 to-cyan-500 text-white shadow-sm border-none">
          <CardContent className="p-3 flex flex-col gap-1">
            <span className="text-[11px] uppercase tracking-wide opacity-80">
              Pending
            </span>
            <span className="text-lg font-semibold">
              {statusCounts.Pending.toString().padStart(2, "0")}
            </span>
          </CardContent>
        </Card>
        <Card className="rounded-xl bg-linear-to-r from-purple-500 to-pink-500 text-white shadow-sm border-none">
          <CardContent className="p-3 flex flex-col gap-1">
            <span className="text-[11px] uppercase tracking-wide opacity-80">
              Preparing
            </span>
            <span className="text-lg font-semibold">
              {statusCounts.Preparing.toString().padStart(2, "0")}
            </span>
          </CardContent>
        </Card>
        <Card className="rounded-xl bg-linear-to-r from-green-500 to-emerald-500 text-white shadow-sm border-none">
          <CardContent className="p-3 flex flex-col gap-1">
            <span className="text-[11px] uppercase tracking-wide opacity-80">
              Ready
            </span>
            <span className="text-lg font-semibold">
              {statusCounts.Ready.toString().padStart(2, "0")}
            </span>
          </CardContent>
        </Card>
        <Card className="rounded-xl bg-linear-to-r from-slate-500 to-gray-500 text-white shadow-sm border-none">
          <CardContent className="p-3 flex flex-col gap-1">
            <span className="text-[11px] uppercase tracking-wide opacity-80">
              Completed
            </span>
            <span className="text-lg font-semibold">
              {statusCounts.Completed.toString().padStart(2, "0")}
            </span>
          </CardContent>
        </Card>
      </div>

      {error && (
        <Card className="border border-red-100 bg-red-50 rounded-xl">
          <CardContent className="p-2.5 flex items-center gap-2 text-xs text-red-800">
            <AlertTriangle className="h-4 w-4" />
            <span>{error}</span>
          </CardContent>
        </Card>
      )}

      {!loading && !error && kots.length === 0 && bills.length === 0 && (
        <Card className="rounded-2xl border border-slate-200 bg-white shadow-sm">
          <CardContent className="p-6 text-center">
            <div className="text-sm text-slate-600 mb-2">No KOTs or bills found</div>
            <div className="text-xs text-slate-400">
              Create bills in POS Billing and mark them as Paid to generate KOTs.
            </div>
          </CardContent>
        </Card>
      )}

      <Tabs defaultValue="auto" className="space-y-3">
        <TabsList className="bg-white border border-slate-200 rounded-full px-1 py-0.5 text-xs flex flex-wrap gap-1">
          <TabsTrigger value="auto">Auto generate</TabsTrigger>
          <TabsTrigger value="send">Send to kitchen</TabsTrigger>
          <TabsTrigger value="modify">Modify order</TabsTrigger>
          <TabsTrigger value="cancel">Cancel item</TabsTrigger>
          <TabsTrigger value="print">Print KOT</TabsTrigger>
          <TabsTrigger value="status">Order status</TabsTrigger>
          <TabsTrigger value="section">Section-wise</TabsTrigger>
          <TabsTrigger value="time">Prep time</TabsTrigger>
          <TabsTrigger value="chef">Chef assignment</TabsTrigger>
          <TabsTrigger value="reprint">Reprint</TabsTrigger>
        </TabsList>

        <TabsContent value="auto" className="space-y-3">
          <AutoGenerateKOT bills={bills} kots={kots} onRefresh={loadData} />
        </TabsContent>

        <TabsContent value="send" className="space-y-3">
          <SendToKitchen bills={bills} kots={kots} onRefresh={loadData} />
        </TabsContent>

        <TabsContent value="modify" className="space-y-3">
          <ModifyOrder kots={kots} onRefresh={loadData} />
        </TabsContent>

        <TabsContent value="cancel" className="space-y-3">
          <CancelItem kots={kots} onRefresh={loadData} />
        </TabsContent>

        <TabsContent value="print" className="space-y-3">
          <KOTPrinting kots={kots} onRefresh={loadData} />
        </TabsContent>

        <TabsContent value="status" className="space-y-3">
          <OrderStatusTracking kots={kots} onRefresh={loadData} />
        </TabsContent>

        <TabsContent value="section" className="space-y-3">
          <SectionWiseKOT kots={kots} onRefresh={loadData} />
        </TabsContent>

        <TabsContent value="time" className="space-y-3">
          <PreparationTimeTracking kots={kots} onRefresh={loadData} />
        </TabsContent>

        <TabsContent value="chef" className="space-y-3">
          <ChefAssignment kots={kots} onRefresh={loadData} />
        </TabsContent>

        <TabsContent value="reprint" className="space-y-3">
          <ReprintKOT kots={kots} onRefresh={loadData} />
        </TabsContent>
      </Tabs>
    </main>
  )
}
